### ISSUE TITLE
задача по PVT 1

### ISSUE THREAD

**Issue by khabibullinra** [unifloc/unifloc#1]
Надо сделать класс OilGeneral который мог бы считать основные свойства нефти самым простым способом - прямыми линиями 
свойства - газосодержание, плотность, вязкость, объемный коэффициент, сжимаемость 
и сделать тест, который смог бы рисовать графики этих зависимостей (рассчитывать их для определенного диапазона входных данных)

**Comment by KhalikovRuslan** [comment]
Добавлены шаблоны создания атрибутов (PVT) - газосодержание, плотность, объемный коэффициент, вязкость, сжимаемость.

Написан простенький код для построения графиков

**Comment by KhalikovRuslan** [comment]
Проблемы: надписи на графиков накладываются друг на другу.

Метод построения графиков, пока не понятно куда отнести.

**Comment by khabibullinra** [comment]
чтобы графики не наползали друг на друга надо поправить расстояние между графиками - должны быть соответствующие параметры - вертикальный и горизонтальный спейсинг 

пока графики лучше вынести из кода расчета в отдельную процедуру - потом посмотрим, что можно сделать лучше

**Comment by KhalikovRuslan** [comment]
Немного поправил код по test3().
Графики строятся лучше, но есть еще потенциал для доработки.
Пока оставлю как есть и займусь следующей задачей.
