### ISSUE TITLE
Сделать расчет z фактора газа в новом классе для газа

### ISSUE THREAD

**Issue by khabibullinra** [unifloc/unifloc#2]
Сделать расчет z фактора газа в новом классе для газа
заголовок класса я сделал - надо туда вставить расчет z фактора по Дранчуку из VBA или того, что делали ранее и сделать тест с отрисовкой графиков для этого расчета

**Comment by KhalikovRuslan** [comment]
Сделано

**Comment by AlexeyVodopyan** [comment]
а остался это файл?

**Comment by khabibullinra** [comment]
насколько я понимаю должно остаться тут в ветке Руслана
посмотри тут https://github.com/khabibullinra/unifloc/blob/ruslan_update/test/PVT_gas.py

**Comment by khabibullinra** [comment]
Может быть Руслан подскажет
